---
- hosts: all
  connection: local
  become: true
  pre_tasks:
    - name: pre-run | update package cache and update (arch)
      tags: always
      pacman: 
        update_cache: yes
        upgrade: no
      changed_when: False
      when: ansible_distribution in ["Archlinux", "EndeavourOS"]

    - name: pre-run | update package cache and update (debian, etc)
      tags: always
      apt: 
        update_cache: yes
        update_only: yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu" "Pop!_OS"]
  tasks:
  - name: install collections 
    shell: ansible-galaxy collection install -r ./requirements.yml
    when: ansible_distribution in ["Archlinux", "EndeavourOS"]
  - import_tasks: tasks/user.yml
  - import_tasks: tasks/files.yml
  - import_tasks: tasks/packages.yml
