---
- hosts: all
  connection: local
  become: true
  pre_tasks:
    - name: pre-run | update package cache and update (arch)
      tags: always
      pacman: 
        update_cache: yes
        upgrade: no
      changed_when: False
      when: ansible_distribution in ["Archlinux", "EndeavourOS"]

    - name: install requirements
      tags: always 
      pacman:
        name:
          - cronie
      changed_when: False
      when: ansible_distribution in ["Archlinux", "EndeavourOS"]

    - name: pre-run | install requirements (debian, etc)
      tags: always
      apt: 
        name: 
          - cron 
      changed_when: False
      when: ansible_distribution == "Pop!_OS"

    - name: pre-run | update package cache and update (debian, etc)
      tags: always
      apt: 
        upgrade: yes
        name: 
          - cron 
      changed_when: False
      when: ansible_distribution == "Pop!_OS"

    - name: install collections 
      shell: ansible-galaxy collection install -r ./requirements.yml
  tasks:
  - import_tasks: tasks/user.yml
  - import_tasks: tasks/arch_packages.yml
    when: ansible_distribution in ["Archlinux", "EndeavourOS"]
  - import_tasks: tasks/debian_packages.yml
  - import_tasks: tasks/files.yml
