# YAY TO ACCESS AUR REPOSITORY  ----------------------------------------------
- name: disable need for password for pacman to allow yay install
  lineinfile:
    path: /etc/sudoers.d/temp_allow_no_pswd_pacman
    state: present
    line: "ALL ALL=NOPASSWD: /usr/bin/pacman"
    validate: /usr/sbin/visudo -cf %s
    create: yes
- name: Install pip
  pacman:
    update_cache: yes
    name:
      - python-pip
      - python-llfuse
      - python-setuptools
      - python-pexpect

- name: git clone yay-bin repo in to /tmp
  become: no
  git:
    repo: 'https://aur.archlinux.org/yay-bin.git'
    dest: /tmp/yay-bin
    clone: yes

- name: install yay using makepkg
  become: no
  expect:
    chdir: /tmp/yay-bin
    command: makepkg -si
    responses:
      (?i)Proceed with installation: "y"

- name: re-enable need for password for pacman
  file:
    path: /etc/sudoers.d/temp_allow_no_pswd_pacman
    state: absent

- name: set yay options to cleanafter package installation
  become: no
  shell: yay -Y --answerclean All --removemake --cleanafter --save
  args:
    executable: /usr/bin/bash
- name: install packages (arch)
  tags: "aur,package,install"
  become_user: jaziel
  when: ansible_distribution in ["Archlinux", "EndeavourOS"]
  kewlfft.aur.aur:
    use: yay
    name:
      - btop
      - tmux
      - cronie
      - bat
      - stow
      - exa
      - trash-cli
      - rsync
      - autofs
      - vim
      - flatpak
      - tailscale 
      - alacritty 
      - ulauncher
      - protonvpn-cli 
      - lf
      - btrbk-git 
      - btrbk-pac-git 
      - auto-cpufreq 
      - plymouth-git
      - ttf-bitstream-vera 
      - ttf-carlito 
      - ttf-dejavu 
      - ttf-fira-mono 
      - ttf-font-awesome 
      - ttf-hack 
      - ttf-iosevka-nerd 
      - ttf-jetbrains-mono 
      - ttf-liberation 
      - ttf-ms-fonts 
      - ttf-nerd-fonts-symbols-2048-em 
      - ttf-nerd-fonts-symbols-common 
      - ttf-opensans 
      - ttf-ubuntu-mono-nerd 
      - ttf-weather-icons 
      - starship 
      - rofi-bluetooth-git 
    #  - rofi-lbonn-wayland-git 
      - rofi-wifi-menu-git 
      - sway 
      - swayidle 
      - swayimg 
      - swaylock-effects 
      - swaync-git 
      - swaysettings-git
      - networkmanager-dmenu-git
      - fuzzel 
    state: present 

- name: Add the flathub flatpak repository remote to the user installation
  tags: "flatpak,package,install"
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo 
    method: system

- name: install flatpaks
  shell: flatpak install -y --system {{item}}
  with_items: 
    - com.bitwarden.desktop 
    - org.onlyoffice.desktopeditors 
    - us.zoom.Zoom 
    - org.mozilla.Thunderbird 
    - org.signal.Signal 
    - com.discordapp.Discord 
    - com.borgbase.Vorta
  become_user: jaziel
  become: true

- name: pacman - enable color
  lineinfile:
    path: /etc/pacman.conf
    regexp: '^#Color$'
    line: 'Color'

- name: pacman - enable ParallelDownloads = 10
  lineinfile:
    path: /etc/pacman.conf
    regexp: '#ParallelDownloads = 10'
    line: 'ParallelDownloads = 10'
- name: makepkg - enable parallel compilation MAKEFLAGS="-j$(nproc)"
  lineinfile:
    path: /etc/makepkg.conf
    regexp: '#MAKEFLAGS="-j2"'
    line: 'MAKEFLAGS="-j$(nproc)"'
