- name: install packages (arch)
  tags: "aur,package,install"
  when: ansible_distribution in ["Archlinux", "EndeavourOS"]
  kewlfft.aur.aur:
    use: yay
    name:
      - btop
      - tmux
      - cronie
      - bat
      - stow
      - exa
      - rsync
      - autofs
      - vim
      - flatpak
      - tailscale 
      - alacritty 
      - ulauncher
      - protonvpn-cli 
      - lf
      - btrbk-git 
      - btrbk-pac-git 
      - auto-cpufreq 
      - plymouth-git
      - ttf-bitstream-vera 
      - ttf-carlito 
      - ttf-dejavu 
      - ttf-fira-mono 
      - ttf-font-awesome 
      - ttf-hack 
      - ttf-iosevka-nerd 
      - ttf-jetbrains-mono 
      - ttf-liberation 
      - ttf-ms-fonts 
      - ttf-nerd-fonts-symbols-2048-em 
      - ttf-nerd-fonts-symbols-common 
      - ttf-opensans 
      - ttf-ubuntu-mono-nerd 
      - ttf-weather-icons 
      - starship 
      - rofi-bluetooth-git 
    #  - rofi-lbonn-wayland-git 
      - rofi-wifi-menu-git 
      - sway 
      - swayidle 
      - swayimg 
      - swaylock-effects 
      - swaync-git 
      - swaysettings-git
      - networkmanager-dmenu-git
    state: present 

- name: Add the flathub flatpak repository remote to the user installation
  tags: "flatpak,package,install"
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo 
    method: system
  when: ansible_distribution == "Pop!_OS"

- name: install flatpaks
  shell: flatpak install -y --system {{item}}
  with_items: 
    - com.bitwarden.desktop 
    - org.onlyoffice.desktopeditors 
    - us.zoom.Zoom 
    - org.mozilla.Thunderbird 
    - org.signal.Signal 
    - com.discordapp.Discord 
    - com.borgbase.Vorta
  become_user: velociraptor
  become: true
- name: pacman - enable color
  lineinfile:
    path: /etc/pacman.conf
    regexp: '^#Color$'
    line: 'Color'

- name: pacman - enable ParallelDownloads = 10
  lineinfile:
    path: /etc/pacman.conf
    regexp: '#ParallelDownloads = 10'
    line: 'ParallelDownloads = 10'
