- name: install tailscale (Debian)
  become_user: velociraptor
  tags: "apt,package,install"
  shell: curl -fsSL https://tailscale.com/install.sh | sh
  when: ansible_distribution == "Pop!_OS"

- name: get ProtonVPN .deb
  become_user: velociraptor
  get_url:
    url: https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_1.0.3_all.deb
    dest: /tmp/protonvpn-stable-release_1.0.3_all.deb
  when: ansible_distribution == "Pop!_OS"
- name: get ProtonVPN .deb
  become_user: velociraptor
  get_url:
    url: https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_1.0.3_all.deb
    dest: /tmp/protonvpn-stable-release_1.0.3_all.deb
  when: ansible_distribution == "Pop!_OS"

- name: install ProtonVPN .deb 
  become: true
  apt:
    deb: /tmp/protonvpn-stable-release_1.0.3_all.deb
  when: ansible_distribution == "Pop!_OS"

- name: install packages (Debian)
  become: true
  tags: "apt,package,install"
  apt:
    update_cache: yes
    name:
      - btop
      - nala
      - tmux
      - cron
      - rsync
      - vim
      - cmake
      - flatpak
      - tailscale 
      - alacritty 
      - protonvpn 
      - lfm
      - rofi
      - cargo
    state: present 
  when: ansible_distribution == "Pop!_OS"

- name: install starship 
  shell: cargo install starship
  tags: "cargo,package"
  when: ansible_distribution == "Pop!_OS"

- name: Add the flathub flatpak repository remote to the user installation
  tags: "flatpak,package,install"
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: system
  when: ansible_distribution == "Pop!_OS"
- name: install flatpaks
  flatpak:
    name:
      - bitwarden 
      - onlyoffice 
      - Zoom 
      - Thunderbird 
      - Signal 
      - Discord 
      - Vorta
    state: present 
  when: ansible_distribution == "Pop!_OS"

   
