- name: install tailscale (Debian)
  become_user: velociraptor
  tags: "apt,package,install"
  shell: curl -fsSL https://tailscale.com/install.sh | sh
  when: ansible_distribution == "Pop!_OS"

- name: install packages (Debian)
  become: true
  tags: "apt,package,install"
  apt:
    update_cache: yes
    name:
      - btop
      - nala
      - tmux
      - cron
      - rsync
      - vim
      - flatpak
      - tailscale 
      - alacritty 
      - protonvpn 
      - lfm
      - starship 
      - rofi
    state: present 
  when: ansible_distribution == "Pop!_OS"

- name: Add the flathub flatpak repository remote to the user installation
  tags: "flatpak,package,install"
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user
- name: install flatpaks
  flatpak:
    name:
      - com.bitwarden.desktop 
      - org.onlyoffice.desktopeditors 
      - us.zoom.Zoom 
      - org.mozilla.Thunderbird 
      - org.signal.Signal 
      - com.discordapp.Discord 
      - com.borgbase.Vorta
    state: present 
   
