- name: create paths
  tags: "install,file"
  file:
    path: /etc/btrbk 
    owner: root 
    group: root
    state: directory 
- name: create paths
  tags: "install,file"
  file:
    path: /etc/btrbk_logger 
    owner: root 
    group: root
    state: directory 

- name: copy btrbk file
  become_user: root
  tags: "btrbk,install,backup"
  copy:
    src: ./tasks/files/btrbk.conf
    dest: /etc/btrbk/btrbk.conf
    owner: root
    group: root
- name: copy btrbk_pac file
  become_user: root
  tags: "btrbk,install,backup"
  copy:
    src: ./tasks/files/btrbk_pac.conf
    dest: /etc/btrbk/btrbk_pac.conf
    owner: root
    group: root
#- name: set root owner
#  tags: "install,file,btrbk"
#  ansible.builtin.file:
#    path: 
#      - /etc/btrbk/btrbk.conf 
#      - /etc/btrbk/btrbk_pac.conf
#    owner: root 
#    group: root
#    mode: 0644
#    state: file
- name: copy btrbk_logger
  tags: "btrbk_logger,install,backup"
  copy:
    src: ./tasks/files/btrbk_logger.conf 
    dest: /etc/btrbk_logger/ 
    owner: root
    group: root 

#  - name: set wallpaper
#    become_user: jay
#    dconf:
#      key: "/org/gnome/desktop/background/picture-uri"
#      value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"
#
#  - name: set wallpaper position
#    become_user: jay
#    dconf:
#      key: "/org/gnome/desktop/background/picture-options"
#      value: "'zoom'"

#- name: copy .bashrc file
# tags: "bash,install"
#  copy:
#   src: ./bash/.bashrc
#   dest: /home/jaziel/.bashrc
#   owner: jaziel
#   group: jaziel
#  - name: stow dotfiles
#    tags: "install,stow"
#    shell: "stow -d $HOME/.dotfiles/files/* --target $HOME --verbose=2"  
#    register: result  
#    changed_when: 'result.stderr is search("LINK: ")'
- name: create paths
  become_user: jaziel
  tags: "install,dotfiles,file"
  file:
    path: $HOME/.dotfiles/files
    owner: jaziel
    group: jaziel
    state: directory 

- name: cp dotfiles
  become_user: jaziel 
  tags: "install,dotfiles"
  copy:
    src: '{{item}}'
    dest: $HOME/.dotfiles/files
    owner: jaziel
    group: jaziel
  with_items:
    - ./files/.config
    - ./files/tmux
    - ./files/vim
    - ./files/bash

- name: Check if file is not a symbolic link
  stat:
    path: $HOME/.bashrc
  register: file_stat

- name: back up .bashrc
  become_user: jaziel
  shell: mv $HOME/.bashrc $HOME/.bashrc.bk
  when: file_stat.stat.islink is not defined or file_stat.stat.islink == false

- name: stow dotfiles
  become_user: jaziel
  tags: "install,stow"
  stow:
    state: supress
    package: '{{ item }}'
    dir: $HOME/.dotfiles/files
    target: $HOME
  with_items:  
    - .config
    - tmux
    - vim
    - bash

- name: create truenas paths
  tags: "install,file"
  file:
    path: /mnt/truenas
    owner: root 
    group: root
    state: directory 

- name: add line to auto.master
  ansible.builtin.lineinfile:
    path: /etc/auto.master
    line: /mnt/truenas /etc/autofs.nfs --ghost --timeout=60
    owner: root
    group: root
    create: no
- name: add lin to autofs.nfs
  ansible.builtin.lineinfile:
    path: /etc/autofs.nfs
    line: vorta -fstype=nfs4,rw truenas.local:/mnt/ssd-storage/docker/vorta
    owner: root
    group: root
    create: yes
