- name: add ansible user
  user:
    name: velociraptor
    system: yes
- name: add ssh key for simone
  authorized_key:
    user: velociraptor
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJHHyFw2Hoxf6zpNe9L28iwVyET5FQUHAJ1hZQInJWS4 laptop"

- name: set up sudo for ansible user
  copy:
    src: files/sudoer_velociraptor
    dest: /etc/sudoers.d/velociraptor
    owner: root
    group: root
    mode: 0440

- name: add ansible-pull cron job
  cron:
    name: ansible auto-provision
    user: velociraptor
    minute: "*/10"
    job: ansible-pull -o -U https://github.com/jaziel826/.dotfiles.git
