 - name: Restart service autofs, in all cases
   ansible.builtin.service:
     name: libvirtd
     state: started
- name: start vm network 
  shell: sudo virsh net-start default && sudo virsh net-autostart default
- name: add jaziel to vm groups 
  ansible.builtin.user:
    name: jaziel
    shell: /bin/bash
    groups: libvert,libvert-qemu,kvm,input,disk
    append: yes
